### ISSUE TITLE
python版本问题

### ISSUE THREAD

**Issue by zhaoforever** [funcwj/CGMM-MVDR#2]
看介绍里提到python版本还有些问题，请问下最近有修复吗？谢谢。

**Comment by funcwj** [comment]
see [estimate_cgmm_masks.py](https://github.com/funcwj/kaldi-enhan/blob/master/scripts/sptk/estimate_cgmm_masks.py) and [cgmm_trainer.py](https://github.com/funcwj/kaldi-enhan/blob/master/scripts/sptk/libs/cgmm_trainer.py) for details
