### ISSUE TITLE
update phi problem

### ISSUE THREAD

**Issue by zhi93** [funcwj/CGMM-MVDR#3]
phi_noise(t, f) = trace(corre * R_noise_inv) / num_channels;
            phi_noisy(t, f) = trace(corre * R_noisy_inv) / num_channels;
            
            % update lambda
            k_noise = obs' * (R_noise_inv / phi_noise(t, f)) * obs / 2;          
            k_noisy = obs' * (R_noisy_inv / phi_noisy(t, f)) * obs / 2;

 update phi ,  k_noise and k_noisey allways be 2

**Comment by funcwj** [comment]
Yes, the computation is duplicated, k_{n,s} will always equal to number of the channels
